# parameters:
#   - string(name: 'GIT_BRANCH', defaultValue: 'main', description: 'Git branch to build')
#   - choice(name: 'BUILD_TYPE', choices: ['Debug', 'Release'], description: 'Select build type')

properties:
  project_name: ms_template_init
  image_name: jk_app
  image_tag: '0.0.1'

env:
  - PWD
  - CURRENT_GIT_BRANCH

stages:
  init:
    - echo finished loading jenkins_crp.yaml
    - echo project name ${properties.project_name}
    - git branch --show-current
    - echo git branch name ${env.CURRENT_GIT_BRANCH}

  build:
    - docker build -t image_name:image_tag -f docker_file_path .