# parameters:
#   - string(name: 'GIT_BRANCH', defaultValue: 'main', description: 'Git branch to build')
#   - choice(name: 'BUILD_TYPE', choices: ['Debug', 'Release'], description: 'Select build type')

properties:
  project_name: ms_template_init
  image_name: jk_app
  image_tag: '0.0.1'

env:
  - PWD
  - CURRENT_GIT_BRANCH
  - PROJECT_NAME

stages:
  init:
    echo "Current Workspace ${pwd()}"
    echo "List of Files:"
    echo "${fileList}"
    echo "Source Git Branch ${env.BRANCH_NAME}"
    echo 'welcome to Code Review Pipeline'
    echo finished loading jenkins_crp.yaml
    echo project name ${env.PROJECT_NAME}

  build:
    - docker build -t image_name:image_tag -f docker_file_path .