apiVersion: v1
kind: Service
metadata:
  name: web-server-service
  labels:
    app: web-service-app
spec:
  type: LoadBalancer
  selector:
    app: web-server-app
  ports:
    - protocol: TCP
      name: http
      port: 80
      targetPort: 5000